[package]
name = "navigator"
version = "0.1.0"
edition = "2021"


[dependencies]
actix-web = "4"
paperclip = { version = "0.8", features = ["actix4"] }
serde = { version = "1.0", features = ["derive"] }
log = "0.4.18"
env_logger = "0.10.0"